### PR TITLE
Use GitHub workflows to verify JSON schemas, generate types automatically and push to NPM/GitHub

### PR DESCRIPTION
**Pull request by zoton2**
PR is currently a draft as I haven't finished the work yet and wanted to make it to write down my thoughts and get opinions.

A while ago I made a script to generate the types from the schemas but we just ended up committing them to the `master` branch manually and then referencing the GitHub repository in other projects. This obviously meant the types wouldn't be up to date unless the build was done manually, which is easily solved by a GitHub workflow.

The next part is where/how to store the built types, and that's what I'm not sure about. They can go on NPM (I have the `esamarathon` organisation on there) but I'm not sure if we should just make a new version on every commit (at which point I'm not sure how the semantic versioning should work) or it should be done manually via releases/tagging on GitHub (probably a safer idea, and still can automate the actual NPM publishing). Also, should we store the generated types on GitHub too? I'd say it may look "messy" but it's not a bad idea, and if it's automated on a push, they will be up to date.

Not related to the changes, but currently we can't automatically merge this PR because I had to make a dummy workflow file in `master` so I could test it on another branch because of a GitHub limitation; we can just keep the file from this branch when we merge.

I shall update this post if I think of any other concerns.

### CODE REVIEW

**Comment by opl-** [comment]
Using npm for distributing the releases is likely the best option as it will just work, as opposed to other options which usually require extra configuration (woo, lock-in).

Using semver is entirely doable and would be in line with existing conventions. The major could then be used as a checklist of which packages still need to be checked against any breaking changes, while the minor would only have to be bumped when the app needs to use newly available data. Patches would be for fixing oopsies. This also makes it pretty trivial to tell which versions of two apps will be able to work together (which may be useful when working with less frequently changed projects?).

The alternative would be use the major only (with minor and patch always set to 0). This still works with version ranges, and has the benefit of being "easier" because the latest protocol will always be pulled regardless of breaking changes. Problem is, I think this would just encourage being less mindful of the versioning. In theory most incompatible changes would still be caught through type checking, but I think full semver is more useful.

If you want to use semver, you almost have to use manual tagging. Automatically detecting which component of the version should be bumped would be difficult.

I think storing generated types in git would just increase complexity, and make it more annoying with work with the repo (need to remember to pull after every push, extra auto-generated commits in the log). In theory if you need to look at the types, you'll have them in `node_modules` and your editor's hints anyway. If really needed, one option is to keep them in a separate branch.

**Comment by zoton2** [comment]
> Using npm for distributing the releases is likely the best option as it will just work, as opposed to other options which usually require extra configuration (woo, lock-in).

Yeah, my main reasoning for this is just because you can't version manage with NPM and normal GitHub commits, and also currently in NPM v7/v8 there's issues with pulling from GitHub if you don't have the correct SSH stuff set up in your environment (more of an issue with GitHub workflows that I had to work around).

> Using semver is entirely doable and would be in line with existing conventions. The major could then be used as a checklist of which packages still need to be checked against any breaking changes, while the minor would only have to be bumped when the app needs to use newly available data. Patches would be for fixing oopsies. This also makes it pretty trivial to tell which versions of two apps will be able to work together (which may be useful when working with less frequently changed projects?).

Not bad ideas, although my only concern is that I assume `mq-events` overall would be getting the version bump? Obviously then people who depend on this would check what was breaking and see if they need to fix something is the idea correct?

> The alternative would be use the major only (with minor and patch always set to 0). This still works with version ranges, and has the benefit of being "easier" because the latest protocol will always be pulled regardless of breaking changes. Problem is, I think this would just encourage being less mindful of the versioning. In theory most incompatible changes would still be caught through type checking, but I think full semver is more useful.

I think the semver idea above is better, yes. Not many changes are made here anyway so I don't think overhauls/breaking changes will happen much anyway.

> If you want to use semver, you almost have to use manual tagging. Automatically detecting which component of the version should be bumped would be difficult.

Agreed, makes sense, and kinda made sense when I was writing the initial post.

> I think storing generated types in git would just increase complexity, and make it more annoying with work with the repo (need to remember to pull after every push, extra auto-generated commits in the log). In theory if you need to look at the types, you'll have them in `node_modules` and your editor's hints anyway. If really needed, one option is to keep them in a separate branch.

Yeah probably best to just commit them, my only thought was if it would be convenient if you just wanted to view them online or something. An example of something I do already: for my NodeCG bundles where I have GitHub workflows to build them, I ended up just making  new branch that merges in everything and then commits the build files. I think for now we should not do anything because it's the easiest. Just generate types and publish to NPM.

On top of the points above, I'm not sure if anyone uses it yet but I assume we would want to release *all* the files on the repository to NPM, alongside the generated types, just so if you want to reference any raw files in your own project you could.

So from what I can understand, this would be the work flow:
- Make any changes we want to definitions/schemas and commit them.
- Once that is all done, we make a release on GitHub with an appropriate semver and relevant notes on what has changed.
- Said GitHub release above can then automatically generate types and publish all files to NPM.

If this is all good, I'll implement the changes later, as it isn't too much.

**Comment by zoton2** [comment]
Implemented all the changes in the workflow I think, slightly hard to test although some of the workflow code was taken from other repositories of mine where I know it works well.

**Comment by opl-** [comment]
> Not bad ideas, although my only concern is that I assume `mq-events` overall would be getting the version bump? Obviously then people who depend on this would check what was breaking and see if they need to fix something is the idea correct?

Correct. Every time a change is made to the protocol, `mq-events` gets a version bump. If the change is backwards incompatible, the major is bumped. If it's just extra data being added, minor is bumped. This is pretty standard usage of semver.

When the major is bumped, all applications are reviewed to ensure they weren't using the part of the protocol which changed, then their dependency on `mq-events` is bumped to use the new major.

When the minor is bumped, only applications which make use of the new data (either for publishing or receiving) are updated to depend on `mq-events` starting from that specific version. All other applications can be left alone, as they can still operate just fine on the old version of `mq-events`.

> [...] I assume we would want to release _all_ the files on the repository to NPM, alongside the generated types, just so if you want to reference any raw files in your own project you could.

I agree; having access to the JSON schema files could be useful for data validation.

> So from what I can understand, this would be the work flow: [...]

That checks out. Could also have a separate workflow which would validate the schemas for every commit even if no release is created for it.

> Implemented all the changes in the workflow I think, [...]

I believe the workflow you currently have will push a release commit before validating that the build is passing (`git push` is executed before `npm run types`). I think moving `git push` to the end of that workflow would fix this?

I would also add the word `Release` to the release commits instead of using the version alone. Makes it easier to filter for them.

**Comment by zoton2** [comment]
> Could also have a separate workflow which would validate the schemas for every commit even if no release is created for it.

Shall look into doing this, either we trigger the build and just don't use it (not sure if this gives errors with bad schemas, I'd assume so) or I implement another library, which I've done once before so I should be able to do it easily.

> I believe the workflow you currently have will push a release commit before validating that the build is passing (git push is executed before npm run types). I think moving git push to the end of that workflow would fix this?

Have split that step up; moved `npm version`/`git commit` between `npm run types` and `npm publish`, and then put the final `git push` at the end; did that so the version is updated in the package file before it is published to NPM, I think that should be OK?

> I would also add the word Release to the release commits instead of using the version alone. Makes it easier to filter for them.

Have done this.

**Comment by zoton2** [comment]
Have added the basis of a validation script, no workflow for it yet but that's easy enough. The current issue is some of our stuff doesn't validate correctly using those methods; the biggest issue being that apparently `"$schema": "../../schemas/event-schema.json",` isn't actually a valid reference, although it also flags an error in VS Code when I look at the files, it still actually uses that file. The other issue I've seen so far is when a definition references the main schema, for example `"$ref": "schemas/event-schema.json#/definitions/timestampObject",`, it doesn't validate it correctly; it works just fine with the type generation however (although I think that's due to seeing the generation to use a specific working directory).

**Comment by zoton2** [comment]
Have tweaked that validation script some more, uses the `ajv` library, mostly good now I think when doing some local tests, hopefully if it doesn't find certain issues or finds too much we can fix it later. Have also incorporated this new script into the old workflow, which also validates by generating the types (which can tell you if certain file/URI `$ref`s don't work). That workflow will also happen on push now, but it will not bump/publish in that case for obvious reasons.

**Comment by opl-** [comment]
> [...] the biggest issue being that apparently `"$schema": "../../schemas/event-schema.json",` isn't actually a valid reference, [...]

I believe this might have to do with the URI not containing the scheme? As per the [specification](https://json-schema.org/draft/2020-12/json-schema-core.html#keyword-schema):

*"The value of this keyword MUST be a URI (containing a scheme) and this URI MUST be normalized. [...]"*

Prefixing it with `file:` might prevent it from complaining.

In practice it might be most standard compliant to use an HTTP URI on some ESA domain for the identifiers, as long as it doesn't prevent tooling from being able to resolve the schema files from our local files. If it confuses the tooling then I'd say it's probably not worth the effort and we should just stick with the current solution (potentially with the `file:` scheme).

The change to `$ref` properties is the correct way of handling this. I'm not sure why I didn't include the `../../` myself.

**Comment by zoton2** [comment]
For context, that comment was only about the `$schema` field, the `$ref` fields that reference another file aren't detected by `ajv` but once it hits `json-schema-to-typescript` that is able to tell if it's valid or not, so I think in that case it's OK. I tried adding `file` in front of one of those `$ref`s and intentionally added an error and my validation script ran fine, so I think for verifying those it's best left to the type script anyway.

Also, for the `$schema` part I actually cheated a bit in my checking code, it just assumes they all use the same base schema (which is currently true) and loads in the base schema, then replaces the `$schema` property with the actual `$id` as specified in the base schema file, which works fine in verifying it. I did originally make it load the base schema each time so it could check the base was valid, but I thought I'd just hardcode it for us for now as it's always the same.

I actually found out the "invalid reference" part from VS Code, which I'm not sure what it uses/does internally but it'll show warnings in the editor. Funnily enough the `$schema` *is* resolved correctly (if you make a change to the `$meta` that isn't allowed it'll say), it's just telling you it breaks that rule. If you replace that with the actual `$id` from the base schema file, it can no longer verify that stuff in the editor, so I don't think we can just change that unless we self host it.

Annoyingly, adding `file:` to the start doesn't work and also breaks the checking the VS Code editor; changing it to `"$schema": "file:../../schemas/event-schema.json",` then gives the error `Unable to load schema from '\..\..\schemas\event-schema.json': ENOENT: no such file or directory, open 'c:\schemas\event-schema.json'.` because it doesn't try to resolve it relative. I did a lot of Googling about this the other day and I think it's just a JSON Schema issue. I've only seen the warning thrown in VS Code, the verifier ignores it of course (as I replaced it).

**Comment by opl-** [comment]
Thinking about it, a relative path may not even be a valid `file:` URI. Parsing the scheme only once should be fine speed things up. I'd say that unless there are any other issues with this solution, you're good to go.

**Pull request merged**
